### ISSUE TITLE
[Bug] 在点选“动作捕捉”/“设置”均无反应

### ISSUE THREAD

**Issue by 8MiYile** [xianfei/SysMocap#22]
但是在控制台内抓到了报错
`vue.js:634 [Vue warn]: Error in render: "TypeError: Cannot read properties of undefined (reading 'substr')"

(found in <Root>)
warn @ vue.js:634
logError @ vue.js:1902
globalHandleError @ vue.js:1897
handleError @ vue.js:1857
Vue._render @ vue.js:3574
updateComponent @ vue.js:4082
get @ vue.js:4494
run @ vue.js:4569
flushSchedulerQueue @ vue.js:4327
（匿名） @ vue.js:1998
flushCallbacks @ vue.js:1924
Promise.then（异步）
timerFunc @ vue.js:1951
nextTick @ vue.js:2008
queueWatcher @ vue.js:4419
update @ vue.js:4559
notify @ vue.js:745
reactiveSetter @ vue.js:1070
proxySetter @ vue.js:4643
onclick @ framework.html:1136
vue.js:1906 TypeError: Cannot read properties of undefined (reading 'substr')
    at Proxy.eval (eval at createFunction (vue.js:11698:14), <anonymous>:4:15313)
    at Vue._render (vue.js:3572:24)
    at Vue.updateComponent (vue.js:4082:23)
    at Watcher.get (vue.js:4494:27)
    at Watcher.run (vue.js:4569:24)
    at flushSchedulerQueue (vue.js:4327:15)
    at Array.<anonymous> (vue.js:1998:14)
    at flushCallbacks (vue.js:1924:16)`
这个是点击动作后捕获的
点击设置后也一样

![image](https://user-images.githubusercontent.com/25455400/174193453-b1dcf7d6-c6a0-4001-bd39-0f19e1005bfe.png)
执行界面还莫名其妙带了GTK窗口边框和菜单栏 
菜单栏是Electron提供的

**Comment by xianfei** [comment]
Same as [#8](https://github.com/xianfei/SysMocap/issues/8)

把mainview/framework.html里面的`glRenderer.substr(7,glRenderer.length-8)`改成`glRenderer?.substr(7,glRenderer.length-8)` 就行了

**Comment by 8MiYile** [comment]
已解决 感谢
